### ISSUE TITLE
Problem trying to setup project on Eclipse/Netbeans

### ISSUE THREAD

**Issue by dzuleta** [Appdynamics/snmptrap-alerting-extension#3]
When I clone the project i have all the package names as: package com.appdynamics.extensions.snmp;

In Eclipse and netbeans it expect to have folders in the following order:
|com
|-appdynamics
|--extensions
|---snmp 

I have also tried to import it using maven import, but it didnt fix the folder structure. Could you please guide me how to setup the development environment? 

(I have a bug that generates when the controller executes the jar. Controller version is 4.0.x)
I can fix it myself, but I can't replicate the development environment.

PD: I guess i could change the folder structure, but i wouldn't be able to upload the patch to the project.

![folder structure problem](https://cloud.githubusercontent.com/assets/5929034/20447906/21898236-adc0-11e6-9a61-7cbaad330860.png)
![index out of bounds bug](https://cloud.githubusercontent.com/assets/5929034/20447907/2189e0b4-adc0-11e6-8e72-b4696aa35812.png)

**Comment by kunalgupApDx** [comment]
TRy doing the below 

git clone https://github.com/Appdynamics/snmptrap-alerting-extension
cd snmptrap-alerting-extension
mvn clean install


This should build the extension. You can then import it in Eclipse as an existing Maven application.
